### ISSUE TITLE
Static ID's of different notes 

### ISSUE THREAD

**Issue by the-iter8** [the-iter8/Noted#8] opened 2022-04-24 22:05 UTC
While I was working on the edit tool, I found out that, deleting N number of entries in the middle of two entries, does not affect the ids of the end entries. 

For example, say user inputs the following
1. Note one
2.  Note two
3. Hehe

Now removing the middle one using the delete button, Will definitely cause it to be popped out but it DOES NOT change the IDs of the 1st and the 3rd one.

The 3rd one should get dynamically updated, with GET/POST request from the database as the new 2nd position guy but it doesn't.

It messes up the editing function as well. Please fix this, ASAP.

**Comment by abhishak3** [comment] 2022-04-25 06:27
It's not a bug its a feature! 
Implementing id's for notes first I made it work as you wanted. Thier ids were changing on every deletion but I was using them as note's database id for deleting.
So, on deleting Note2. Note 3 now has id=2. But on deleting Note3 I was trying to delete id=2 from database but Note 2 has id=2 so it was not found in database hence error was thrown. So, I used their real database id instead.
But if it is causing problem. Let me come up with an alternative.

**Comment by the-iter8** [comment] 2022-05-01 17:10
ok

**Comment by abhishak3** [comment] 2022-05-01 18:17
I hope you understood that!

**Comment by abhishak3** [comment] 2022-05-02 17:16
It's fixed now!

**Comment by the-iter8** [comment] 2022-05-02 17:16
weird flex but ok

**Closed as completed by abhishak3** 2022-05-02 17:16 UTC
Labels: bug, database
